#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Windows 环境 TIA Openness 初始化脚本
.DESCRIPTION
    1. 检测 TIA Portal 安装路径与 Siemens.Engineering.dll
    2. 将当前用户加入 "Siemens TIA Openness" 本地用户组
    3. 写入用户级环境变量 TIA_OPENNESS_DLL_PATH
    4. 生成 config/siemens_config.yaml 供 Python 端读取
    5. 检查并尝试安装 pythonnet
.PARAMETER TiaVersion
    TIA Portal 版本，例如 V19、V18、V17。默认自动检测最高版本。
.EXAMPLE
    powershell scripts/setup_tia_openness.ps1
    powershell scripts/setup_tia_openness.ps1 -TiaVersion "V18"
#>
param(
    [string]$TiaVersion = ""
)

$ErrorActionPreference = "Stop"

function Get-TiaPortalRoots {
    return @(
        "C:\Program Files\Siemens\Automation",
        "E:\Program Files\Siemens\Automation",
        "D:\Program Files\Siemens\Automation"
    )
}

function Get-AvailableTiaVersions {
    $found = @()
    foreach ($root in Get-TiaPortalRoots) {
        if (-not (Test-Path $root)) { continue }
        Get-ChildItem -Path $root -Filter "Portal V*" -Directory -ErrorAction SilentlyContinue | ForEach-Object {
            if ($_.Name -match "Portal V(\d+)") {
                $found += [PSCustomObject]@{
                    Version = $matches[1]
                    Root    = $root
                }
            }
        }
    }
    return $found | Sort-Object -Property { [int]$_.Version } -Descending
}

function Find-TiaOpennessDll {
    param(
        [string]$Version
    )
    $roots = Get-TiaPortalRoots
    $candidates = @(
        "Portal $Version\Bin\PublicAPI",
        "Portal $Version\PublicAPI\$Version"
    )
    foreach ($root in $roots) {
        foreach ($candidate in $candidates) {
            $p = Join-Path $root $candidate
            $dll = Join-Path $p "Siemens.Engineering.dll"
            if (Test-Path $dll) {
                return $dll
            }
        }
    }
    return $null
}

Write-Host "=== TIA Openness 环境初始化 ===" -ForegroundColor Cyan

# 自动检测版本
if ([string]::IsNullOrWhiteSpace($TiaVersion)) {
    $available = Get-AvailableTiaVersions
    if ($available.Count -eq 0) {
        Write-Error "未检测到任何 TIA Portal 安装。请确认已安装 TIA Portal 与 Openness 组件。"
        exit 1
    }
    $detected = $available[0].Version
    $TiaVersion = "V$detected"
    Write-Host "自动检测到 TIA Portal 版本: $TiaVersion" -ForegroundColor Green
}

$dllPath = Find-TiaOpennessDll -Version $TiaVersion
if (-not $dllPath) {
    Write-Error "未找到 TIA Portal $TiaVersion 的 Siemens.Engineering.dll。`n请确认：
1. 已安装 TIA Portal $TiaVersion
2. 安装时勾选了 Openness / Openness API 组件
3. 如果安装在非默认路径，请修改本脚本中的 Get-TiaPortalRoots"
    exit 1
}
Write-Host "找到 TIA Openness DLL: $dllPath" -ForegroundColor Green

# 将当前用户加入 Siemens TIA Openness 组
$group = "Siemens TIA Openness"
try {
    $groupInfo = net localgroup $group 2>$null
    $isMember = $groupInfo | Select-String -Pattern "\b$([regex]::Escape($env:USERNAME))\b"
    if ($isMember) {
        Write-Host "当前用户已在 `"$group`" 组中" -ForegroundColor Green
    } else {
        Write-Host "将当前用户加入 `"$group`" 组，这是调用 Openness API 的必需权限..." -ForegroundColor Yellow
        net localgroup $group $env:USERNAME /add | Out-Null
        Write-Host "加入成功。请注销并重新登录 Windows，使权限生效。" -ForegroundColor Green
    }
} catch {
    Write-Warning "无法自动加入 `"$group`" 组：$_"
    Write-Host "请手动操作：计算机管理 -> 本地用户和组 -> 组 -> Siemens TIA Openness，添加当前用户。" -ForegroundColor Yellow
}

# 设置用户级环境变量
[Environment]::SetEnvironmentVariable("TIA_OPENNESS_DLL_PATH", $dllPath, "User")
$env:TIA_OPENNESS_DLL_PATH = $dllPath
Write-Host "已设置用户环境变量 TIA_OPENNESS_DLL_PATH = $dllPath" -ForegroundColor Green

# 生成/更新配置文件
$configDir = Join-Path $PSScriptRoot ".." "config"
New-Item -ItemType Directory -Force -Path $configDir | Out-Null
$configFile = Join-Path $configDir "siemens_config.yaml"
$yamlPath = $dllPath -replace '\\', '/'
@"
# Siemens TIA Openness configuration (auto-generated by setup_tia_openness.ps1)
tia_portal_version: "$TiaVersion"
tia_openness_dll_path: "$yamlPath"
"@ | Out-File -FilePath $configFile -Encoding utf8
Write-Host "已生成配置文件: $configFile" -ForegroundColor Green

# 检查 pythonnet
Write-Host "检查 pythonnet ..." -ForegroundColor Cyan
$python = Get-Command python -ErrorAction SilentlyContinue
if (-not $python) { $python = Get-Command python3 -ErrorAction SilentlyContinue }
if ($python) {
    & $python.Source -c "import clr" 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "未检测到 pythonnet，尝试安装..." -ForegroundColor Yellow
        & $python.Source -m pip install "pythonnet>=3.0.5"
    } else {
        Write-Host "pythonnet 已安装" -ForegroundColor Green
    }
} else {
    Write-Warning "未找到 python/python3，请手动执行 pip install pythonnet>=3.0.5"
}

Write-Host "`n初始化完成。" -ForegroundColor Cyan
Write-Host "注意：如果这是第一次加入 Openness 用户组，请注销并重新登录 Windows，权限才会生效。" -ForegroundColor Yellow
